import assert from "node:assert/strict";
import fs from "node:fs";
import { test } from "node:test";
import { deformitySeries, forecastSeries, fruitSeries, gaussianSeries, growthRange, growthSeries, overviewSeries, recurringSeries } from "../src/series.js";

const fixturePath = process.env.FRUITCAM_FIXTURES;
const F = fixturePath ? JSON.parse(fs.readFileSync(fixturePath, "utf8")) : null;
const skip = F ? false : "set FRUITCAM_FIXTURES (generated by core.test_dashboard)";
const near = (a, b, tol, what) => assert.ok(Math.abs(a - b) <= tol, `${what}: |${a} - ${b}| > ${tol}`);
const say = (...a) => console.log("    ", ...a);

test("1 deformity: the highlighted segment is the true dominant type of every week", { skip }, () => {
  const { payload, truth } = F.deformity;
  const s = deformitySeries(payload);
  let correct = 0;
  let worst = 0;
  truth.dominant.forEach((top, w) => {
    if (top === "none") {
      assert.ok(s.types.every((t) => s.dominant[t][w] === false && s.shares[t][w] === null), `week ${w} should be empty`);
      return;
    }
    if (top === "tie") {
      assert.ok(s.types.every((t) => s.dominant[t][w]), `week ${w} tie should highlight all`);
      return;
    }
    assert.ok(s.dominant[top][w] && s.types.filter((t) => s.dominant[t][w]).length === 1, `week ${w} should highlight only ${top}`);
    correct++;
    worst = Math.max(worst, Math.abs(s.shares[top][w] - 0.6));
  });
  near(worst, 0, 0.1, "dominant share vs true 0.6");
  assert.deepEqual(s.empty, truth.empty);
  assert.equal(s.latest.type, truth.dominant[truth.dominant.length - 1]);
  const sums = payload.weeks.map((_, w) => s.types.reduce((a, t) => a + (s.shares[t][w] ?? 0), 0)).filter((v) => v > 0);
  sums.forEach((v) => near(v, 1, 1e-12, "stacked shares sum"));
  say(`highlighted = true dominant in ${correct}/${correct} weeks; max |share-0.6| = ${worst.toFixed(4)}; empty weeks ${JSON.stringify(s.empty)}; stacked sums = 1`);
});

test("2 forecast: history, fan and forecast point match the known trend", { skip }, () => {
  const { payload, truth } = F.forecast;
  const items = Object.fromEntries(payload.sectors.map((x) => [x.sector, forecastSeries(x, payload.labels, payload.target_period)]));
  const r = items.rising;
  const n = r.labels.length - 1;
  near(r.forecast[n], truth.rising_next, 0.03, "forecast point vs true next value");
  assert.ok(r.lo[n] <= truth.rising_next && truth.rising_next <= r.hi[n], "true value inside the fan at the forecast point");
  assert.equal(r.forecast[r.last], r.history[r.last]);
  assert.equal(r.hi[r.last], r.history[r.last]);
  assert.equal(r.lo[r.last], r.history[r.last]);
  const err = Math.max(...truth.line.map((v, i) => Math.abs(r.history[i] - v)));
  near(err, 0, 0.05, "history vs true line");
  assert.ok(r.historyN.slice(0, n).every((v) => v === truth.n_week), "per-period n");
  const short = items.short;
  assert.equal(short.ok, false);
  assert.ok([...short.forecast, ...short.hi, ...short.lo].every((v) => v === null), "no fan for insufficient data");
  say(`rising: point ${r.forecast[n].toFixed(4)} (truth ${truth.rising_next}), fan [${r.lo[n].toFixed(4)}, ${r.hi[n].toFixed(4)}], max |history - truth| = ${err.toFixed(4)}, n per period = ${truth.n_week}`);
  say(`short: ok=${short.ok}, observed=${short.observed}, fan all null`);
});

test("3 fruits: bar values and the emphasized winner match the known counts", { skip }, () => {
  const s = fruitSeries(F.fruits.payload);
  assert.deepEqual(s.labels, F.fruits.truth.labels);
  assert.deepEqual(s.values, F.fruits.truth.values);
  assert.deepEqual(s.winners, [true, false, false]);
  const tie = fruitSeries(F.fruits_tie.payload);
  assert.equal(tie.tie, true);
  assert.deepEqual(tie.winners.filter(Boolean).length, 2);
  say(`values ${JSON.stringify(s.values)}, winner ${s.labels[s.winners.indexOf(true)]}; tie scenario winners ${JSON.stringify(tie.winners)}`);
});

for (const [n, kind, rate] of [["4", "good", 0.1], ["5", "rotten", 0.2]]) {
  test(`${n} growth ${kind}: bars equal the known +${rate * 100}% per month, first period is n/a`, { skip }, () => {
    const s = growthSeries(F.growth.payload, kind);
    const err = Math.max(...s.count.slice(1).map((v) => Math.abs(v - rate)));
    near(err, 0, 0.003, `${kind} count growth`);
    assert.deepEqual(s.na, [0]);
    assert.deepEqual(s.sign.slice(1), Array(s.sign.length - 1).fill(1));
    assert.equal(s.last.index, s.count.length - 1);
    const range = growthRange(F.growth.payload);
    assert.equal(range.min, -range.max);
    say(`max |bar - ${rate}| = ${err.toExponential(1)}, n/a at ${JSON.stringify(s.na)}, shared range ±${range.max.toFixed(3)}`);
  });
}

test("4/5 growth with previous = 0: n/a markers exactly where growth is undefined, never zero", { skip }, () => {
  const g = growthSeries(F.growth_zero.payload, "good");
  const r = growthSeries(F.growth_zero.payload, "rotten");
  assert.deepEqual(g.na, F.growth_zero.truth.good_na);
  assert.deepEqual(r.na, F.growth_zero.truth.rotten_na);
  assert.equal(g.count[1], -1);
  assert.equal(g.sign[1], -1);
  near(r.count[3], 0.5, 1e-12, "rotten Apr");
  assert.ok([...g.na, ...r.na].every((i) => (i < g.count.length ? true : false)));
  assert.ok(g.na.every((i) => g.count[i] === null) && r.na.every((i) => r.count[i] === null));
  say(`good n/a ${JSON.stringify(g.na)}, rotten n/a ${JSON.stringify(r.na)}, good Feb ${g.count[1]}, rotten Apr ${r.count[3]}`);
});

test("6 recurring: peak bins match the known seasonal pattern in every view", { skip }, () => {
  const { payload, truth } = F.recurring;
  const m = recurringSeries(payload, "month");
  const se = recurringSeries(payload, "season");
  assert.equal(m.buckets[m.peakRotten], truth.month_peak_rotten);
  near(m.rotten[m.peakRotten], truth.month_peak_rotten_value, 1e-12, "rotten peak value");
  assert.equal(m.buckets[m.peakGood], truth.month_peak_good);
  assert.equal(se.buckets[se.peakGood], truth.season_peak_good);
  assert.equal(se.buckets[se.peakRotten], truth.season_peak_rotten);
  near(se.good[se.peakGood], truth.season_peak_good_value, 1e-12, "season good peak");
  near(se.rotten[se.peakRotten], truth.season_peak_rotten_value, 1e-12, "season rotten peak");
  const w = recurringSeries(payload, "week");
  assert.ok(w.maxN <= 3 && w.buckets.length > 0);
  say(`month peaks: rotten ${m.buckets[m.peakRotten]} (${m.rotten[m.peakRotten].toFixed(4)}), good ${m.buckets[m.peakGood]}; season peaks: good ${se.buckets[se.peakGood]} (${se.good[se.peakGood].toFixed(4)}), rotten ${se.buckets[se.peakRotten]} (${se.rotten[se.peakRotten].toFixed(4)})`);
});

test("7 gaussian: mean, std, sigma bands and histogram match the generator", { skip }, () => {
  const { payload, truth } = F.gaussian;
  const items = Object.fromEntries(payload.sectors.map((x) => [x.sector, gaussianSeries(x)]));
  for (const name of ["A", "B"]) {
    const s = items[name];
    const t = truth[name];
    near(s.mean, t.mu, 0.01, `${name} mean`);
    near(Math.abs(s.std - t.sd_eff) / t.sd_eff, 0, 0.15, `${name} std (relative)`);
    near(s.sigma1[0], s.mean - s.std, 1e-12, "sigma1 low");
    near(s.sigma2[1], s.mean + 2 * s.std, 1e-12, "sigma2 high");
    near(s.bins.reduce((a, b) => a + b.y * b.width, 0), 1, 1e-9, `${name} histogram area`);
    assert.equal(s.bins.reduce((a, b) => a + b.count, 0), s.n);
    assert.equal(s.qq.length, s.n);
    say(`${name}: mean ${s.mean.toFixed(4)} (truth ${t.mu}), std ${s.std.toFixed(4)} (expected ${t.sd_eff.toFixed(4)}), histogram area 1, bins count ${s.n} periods, flagged=${s.flagged}`);
  }
  assert.equal(items.C.flagged, true);
  assert.ok(items.C.range[0] < 0, "skewed sector curve extends below 0%");
  say(`C: flagged=${items.C.flagged} reasons=${JSON.stringify(items.C.reasons)}, curve starts at ${(items.C.range[0] * 100).toFixed(1)}% (impossible zone drawn)`);
});

test("8 overview: per-period rate and per-sector rates match the known counts", { skip }, () => {
  const { payload, truth } = F.overview;
  const s = overviewSeries(payload);
  assert.ok(s.rate.every((v) => Math.abs(v - truth.rate) < 1e-12));
  assert.deepEqual(s.sectors, truth.sectors);
  s.sectorRates.forEach((v, i) => near(v, truth.sector_rates[i], 1e-12, `sector ${s.sectors[i]}`));
  assert.equal(s.total, truth.total);
  near(s.rottenRate, truth.rate, 1e-12, "overall rate");
  say(`rate per period ${JSON.stringify(s.rate)}, sectors ${JSON.stringify(s.sectors)} rates ${JSON.stringify(s.sectorRates)}, total ${s.total}`);
});

test("motion budget: every keyframe and transition animates only transform or opacity", () => {
  const css = fs.readFileSync(new URL("../src/style.css", import.meta.url), "utf8");
  const bad = [];
  let i = 0;
  while ((i = css.indexOf("@keyframes", i)) >= 0) {
    let depth = 0;
    let j = css.indexOf("{", i);
    const start = j;
    for (; j < css.length; j++) {
      if (css[j] === "{") depth++;
      if (css[j] === "}" && --depth === 0) break;
    }
    const name = css.slice(i, start).trim();
    for (const m of css.slice(start, j).matchAll(/([a-z-]+)\s*:/g)) if (!["opacity", "transform"].includes(m[1])) bad.push(`${name}: ${m[1]}`);
    i = j;
  }
  const transitions = [...css.matchAll(/(?<![-\w])transition\s*:\s*([^;]+);/g)].map((m) => m[1]);
  for (const decl of transitions) for (const part of decl.split(/,(?![^(]*\))/)) if (!["opacity", "transform"].includes(part.trim().split(/\s+/)[0])) bad.push(`transition: ${part.trim()}`);
  say(`checked ${css.split("@keyframes").length - 1} keyframes and ${transitions.length} transition declarations`);
  assert.deepEqual(bad, []);
});
