export const t = {
  app: {
    name: "FruitCam_ai",
    tagline: "Câmeras e IA na esteira: cada fruta contada, classificada e medida · foco atual: caju",
    skip: "Pular para o conteúdo",
    navLabel: "Navegação principal",
    navLine: "Linha",
    navAnalyze: "Inspeção por foto",
    navInspect: "Inspeção",
    navDashboard: "Painel",
    navHow: "Como funciona",
    navHowShort: "Método",
    navCredits: "Créditos e licenças",
    navCreditsShort: "Créditos",
    navGroups: { operation: "Operação", analysis: "Análise", about: "Sobre" },
    account: "Conta",
    login: "Entrar",
    logout: "Sair",
    signedAs: "Conectado como",
    demoBadge: "Dados de demonstração",
    demoBadgeHint: "Estes números vêm de dados sintéticos, não de inspeções reais.",
  },
  login: {
    title: "Entrar",
    subtitle: "Acesso restrito à equipe. Contas são criadas pelo administrador.",
    username: "Usuário",
    password: "Senha",
    submit: "Entrar",
    submitting: "Entrando…",
  },
  upload: {
    title: "Inspeção por foto",
    subtitle: "Para conferir uma fruta fora da esteira: uma fruta por foto, sobre fundo claro e liso. A linha de produção usa a câmera fixa (página Linha).",
    sector: "Setor",
    sectorPlaceholder: "Ex.: setor norte",
    fruit: "Tipo de fruta",
    dropTitle: "Coloque a foto aqui",
    dropHint: "Arraste e solte, ou clique para escolher (JPEG, PNG ou WebP)",
    dropActive: "Solte para carregar a foto",
    camera: "Usar câmera",
    change: "Trocar foto",
    submit: "Analisar",
    submitting: "Analisando…",
    again: "Nova análise",
    missing: "Escolha a foto, o setor e o tipo de fruta.",
    badType: "Formato não aceito. Use JPEG, PNG ou WebP.",
    result: "Resultado",
    good: "Boa",
    rotten: "Podre",
    confidence: "Confiança do modelo",
    confidenceNote: "Confiança é a probabilidade atribuída pelo modelo, não uma acurácia verificada.",
    deformity: "Tipo de defeito",
    time: "Tempo de inferência",
    oneFruit: "A caixa marca a maior região escura da foto; o modelo classifica esse recorte. Um veredito por foto.",
    probs: "Probabilidade por classe (calibrada)",
    review: "Revisão manual: o modelo não tem confiança suficiente para decidir sozinho. Use as probabilidades como sugestão e confira a fruta.",
    model: "Modelo",
    saved: "Registro salvo",
    previewAlt: "Foto enviada para análise",
    scanning: "Analisando a foto…",
  },
  brand: {
    alt: "FruitCam_ai",
    home: "FruitCam_ai, página inicial",
    loading: "Carregando FruitCam_ai…",
  },
  theme: {
    toDark: "Usar tema escuro",
    toLight: "Usar tema claro",
  },
  footer: {
    label: "Rodapé",
    how: "Como funciona",
    credits: "Créditos e licenças",
    honesty: "Protótipo. Linhas e painéis de demonstração usam dados sintéticos e simulação; números de qualidade do modelo aparecem só onde foram medidos, com o conjunto indicado. O desempenho em esteira real ainda não foi avaliado.",
  },
  media: {
    illustrative: "Imagem ilustrativa",
    playVideo: "Reproduzir vídeo",
    play: "Reproduzir",
    pause: "Pausar",
    captionsLabel: "Português (descrição)",
    transcript: "Transcrição",
    syntheticDemo: "Gravação do app · dados sintéticos",
  },
  guide: {
    title: "Como fotografar",
    good: "Assim",
    bad: "Evite",
    tips: ["Uma fruta por foto", "Luz boa e uniforme", "Fundo claro e liso", "Fruta ocupando boa parte da foto"],
    badges: { "guia-varias": "Várias frutas", "guia-longe": "Longe, entre folhas", "guia-escuro": "Pouca luz" },
    note: "Recomendações baseadas no funcionamento atual (classificador + caixa por limiarização); ainda não validadas em campo.",
  },
  fruitStatus: {
    caju: "Modelo treinado com fotos de caju",
    castanha: "Sem fotos de treino: resultado não validado",
    melao: "Sem fotos de treino: resultado não validado",
  },
  pipeline: {
    steps: [
      { title: "Câmera", text: "Câmera industrial fixa sobre a esteira, com luz constante, cerca de 25 quadros por segundo.", ai: false },
      { title: "Segmentação", text: "Separa cada fruta da cor da esteira (espaço de cor Lab) e mede seu tamanho em mm.", ai: false },
      { title: "Rastreamento", text: "Segue cada fruta de quadro em quadro; ela é contada uma única vez ao cruzar a linha.", ai: false },
      { title: "Classificador", text: "MobileNetV3-Small olha a fruta em até 6 quadros: boa, baixa qualidade ou podre.", ai: true },
      { title: "Decisão", text: "Média das vistas; confiança baixa vai para revisão manual. Regra de calibre opcional.", ai: false },
      { title: "Registro", text: "Uma linha por fruta: hora, câmera, lote, classe, tamanho e confiança.", ai: false },
      { title: "Estatística", text: "Frutas por minuto, % por classe com IC 95%, carta de controle e aceite de lote.", ai: false },
    ],
    ai: "IA",
    code: "Código determinístico",
    status: "Etapa {i} de {n}: {title}",
    summary: "7 etapas: só a 4ª usa IA; as outras são código determinístico e testado.",
    replay: "Repetir animação",
  },
  how: {
    title: "Como funciona",
    lead: "Da câmera sobre a esteira ao relatório da linha: o que acontece em cada etapa, o que é IA, o que é código determinístico, o que foi medido e o que ainda não foi validado.",
    pipelineTitle: "O caminho de cada fruta na esteira",
    figuresTitle: "Figuras científicas",
    figuresLead: "Cada figura é gerada por script, a partir de dados sintéticos com resposta conhecida, de simulação ou de medições reais, sempre rotulados. Baixe em SVG ou PNG 300 dpi.",
    figure: "Figura",
    scrollHint: "Deslize para o lado para ver a figura inteira, ou baixe o arquivo.",
    downloadSvg: "SVG",
    downloadPng: "PNG 300 dpi",
    download: "Baixar",
    labels: { schematic: "Esquema, sem dados", synthetic: "Dados sintéticos", real: "Medição real", example: "Exemplo real, não é métrica", test: "Medição real (teste)", simulation: "Simulação" },
    qualityTitle: "Qualidade do modelo: o que foi medido",
    dataIssue: "Correção nos dados: o conjunto público usado no treino (Universidade Makerere, CC BY 4.0) numera as classes de dois jeitos. Em 1.466 das 3.098 fotos, a árvore inteira recebe o número de “podre”. Um modelo anterior parecia acertar 80,9%, mas tinha aprendido esse erro: nas fotos com a numeração do artigo, a acurácia balanceada dele foi de 44%. Essas 1.466 fotos foram excluídas, e o modelo atual foi treinado com as 1.632 restantes, metade das vezes com a fruta recortada e colada sobre esteiras sintéticas.",
    measured: "Teste com {n} recortes de {photos} fotos (só fotos com a numeração do artigo) que não aparecem no treino nem na validação: acurácia {acc} (IC 95% {lo} a {hi}, bootstrap por foto), contra {base} de quem respondesse sempre a classe mais comum, porque “podre” é a maioria do teste. A medida certa aqui é a acurácia balanceada (média da sensibilidade das três classes; o acaso dá 33%): {bal}.",
    perClass: "Sensibilidade por classe: boa {boa}, baixa qualidade {poor}, podre {rotten}. Podres classificadas como boas: {rg} (IC 95% {rglo} a {rghi}).",
    review: "Com o limiar de revisão ({thr}), o sistema decide sozinho {cov} das frutas, com {accd} de acerto; as demais vão para conferência manual.",
    reviewNone: "Nenhum limiar de confiança chegou a 95% de acerto na validação. Por isso o sistema não decide nenhuma fruta sozinho: todas vão para conferência manual, com a sugestão do modelo e as probabilidades.",
    beltText: "Na esteira simulada, com frutas reais de teste recortadas sem as folhas e coladas na esteira: {crossed} frutas cruzaram a linha, {counted} foram contadas, {double} duplicadas. O acerto ponta a ponta foi {acc}, contra {direct} no teste direto dos recortes de campo. {after}",
    beltReview: "Com o limiar de revisão, o sistema decidiu sozinho {cov} das frutas ({accd} de acerto) e mandou o resto para conferência.",
    beltReviewNone: "Sem limiar confiável, nenhuma fruta foi decidida sozinha: todas foram para conferência.",
    limits: "Limite principal: com os dados públicos confiáveis que existem, o classificador é fraco (acurácia balanceada perto de 50%, com o acaso em 33%) e nenhum limiar de confiança chega a 95% de acerto. Hoje o sistema conta e mede cada fruta, mas manda para conferência toda fruta classificada pelo modelo. Para classificar de verdade, é preciso gravar bandejas separadas à mão na sua esteira e treinar de novo (veja DATA_COLLECTION.md). “Baixa qualidade” no treino corresponde a frutos imaturos.",
    pendingTitle: "Ainda não avaliado",
    notEvaluated: "Ainda não avaliado",
    pending: [
      { title: "Teste em esteira real", text: "Falta uma amostra rotulada filmada pela câmera instalada na linha, com a luz e as frutas reais." },
      { title: "Rótulos dos dados públicos", text: "A numeração das classes nas 1.466 fotos excluídas precisa ser confirmada pelos autores do conjunto." },
      { title: "Separação por cor em esteira real", text: "Numa esteira real de batatas, a separação por cor falhou. O caju contrasta muito mais com uma esteira cinza, mas isso ainda não foi testado em esteira real de caju." },
      { title: "Outros defeitos", text: "Amassado, rachado e queimado não estão nos dados de treino; hoje só há imaturo e podre." },
      { title: "Frutas encostadas", text: "Duas frutas que se tocam viram uma só máscara e são contadas como uma." },
      { title: "Castanha e melão", text: "O modelo nunca viu essas frutas no treino; os resultados delas não têm validade." },
    ],
    videoTitle: "Demonstração gravada do app",
    verifiedTitle: "O que foi verificado",
    verified: [
      "Contagem na esteira simulada: cada fruta contada uma única vez, com tamanho medido dentro de poucos por cento (testes automatizados com resposta conhecida).",
      "Carta de controle e aceite de lote contra dados sintéticos com uma piora conhecida.",
      "Que a inspeção por foto devolve exatamente a saída do classificador.",
      "Acurácia do modelo em um teste separado por foto, com as limitações descritas acima.",
      "Rótulos do conjunto público auditados: a numeração trocada em 1.466 fotos foi detectada (teste automatizado) e essas fotos foram excluídas.",
      "A receita de treino numa esteira industrial real de batatas (dados abertos da Universidade de Pardubice, validação cruzada): 90,6% de acerto, mas só 52,7% das batatas danificadas reconhecidas.",
    ],
    notVerifiedTitle: "O que ainda não foi validado",
    notVerified: [
      "O desempenho em esteira real, com a câmera, a luz e as frutas da linha.",
      "Qualquer estatística com dados reais de produção: só existem dados sintéticos e simulação.",
      "Classificação de castanha e de melão.",
      "Defeitos além de imaturo e podre.",
      "A separação da fruta pela cor numa esteira real de caju.",
    ],
  },
  line: {
    title: "Linha de inspeção",
    lead: "Câmera fixa sobre a esteira: cada fruta contada, medida e classificada, minuto a minuto.",
    ctaHow: "Como a câmera funciona",
    heroCaption: "Simulação da esteira processada pelo mesmo código da câmera real. Frutas desenhadas; rótulos vêm da simulação, não do modelo.",
    cameraTitle: "Como a câmera funciona",
    cameraLead: "Do quadro de vídeo à estatística, em seis passos. Só o passo 4 é inteligência artificial; o resto é código determinístico e testado.",
    steps: [
      { title: "A câmera vê a esteira de cima", text: "Câmera industrial fixa (IP/RTSP ou USB), luz constante e fundo uniforme. Cada milímetro da esteira vira um número fixo de pixels, calibrado na instalação (px/mm)." },
      { title: "Separa cada fruta da esteira", text: "Cada pixel é comparado com a cor da esteira no espaço Lab. O que difere vira máscara; regiões pequenas demais são descartadas. Da área sai o diâmetro em mm." },
      { title: "Segue a fruta entre quadros", text: "A fruta anda em linha reta na velocidade da esteira. O rastreador prevê onde ela estará no próximo quadro e liga as detecções: cada fruta ganha um número." },
      { title: "A IA classifica a fruta", text: "Recortes da mesma fruta em até 6 quadros passam pelo classificador (MobileNetV3-Small). A média das probabilidades decide: boa, baixa qualidade ou podre." },
      { title: "Conta uma vez, na linha", text: "A fruta é contada uma única vez, quando cruza a linha tracejada. Quando o modelo não tem confiança suficiente, a fruta vai para revisão manual em vez de arriscar; com o modelo atual, isso vale para todas." },
      { title: "Vira estatística da linha", text: "Cada fruta é um registro. Daí saem frutas por minuto, % de cada classe com IC 95%, a carta de controle que avisa quando a podridão sobe e o aceite de cada lote." },
    ],
    diagram: { camera: "câmera", light: "luz", belt: "esteira", direction: "sentido da esteira", line: "linha de contagem", view: "campo de visão" },
    diagramAlt: "Desenho animado: uma câmera acima da esteira, com o campo de visão marcado; frutas passam da esquerda para a direita e recebem uma caixa colorida ao cruzar a linha de contagem tracejada.",
    monitorTitle: "Linha ao vivo",
    monitorLead: "Escolha a câmera e o período. Os números se atualizam sozinhos.",
    camera: "Câmera",
    period: "Período",
    data: "Dados",
    sources: { real: "Câmeras reais", demo: "Demonstração", all: "Todos" },
    periods: { 30: "30 min", 60: "1 h", 240: "4 h", 480: "8 h", 1440: "24 h" },
    online: "Ao vivo",
    offline: "Câmera desconectada",
    simulated: "Simulação",
    offlineHelp: "Nenhum quadro recente desta câmera. Para ligá-la: python manage.py run_camera {slug}",
    frameAlt: "Último quadro da câmera {name}, com as caixas de cada fruta e a linha de contagem.",
    frameMeta: "{fps} quadros/s · {passages} frutas contadas nesta sessão · decisão: {decider}",
    kpi: {
      throughput: "Frutas por minuto",
      boa: "Boas",
      baixa_qualidade: "Baixa qualidade",
      podre: "Podres",
      revisar: "Para revisão",
      total: "{n} frutas no período",
      ci: "IC 95%: {lo} a {hi}",
    },
    flowTitle: "Fluxo por janela de {w} min",
    flowSub: "Barras empilhadas: frutas por classe em cada janela completa.",
    chartTitle: "Carta de controle: % de podres",
    chartSub: "Pontos: % de podres por janela. Faixa: limites p′ (Laney, 3σ). Losango: alarme.",
    center: "mediana",
    ucl: "limite superior",
    alarms: "Alarmes",
    noAlarms: "Nenhum alarme no período.",
    alarmText: { acima_do_limite: "{time}: % de podres acima do limite superior ({p})", sequencia_acima_da_mediana: "{time}: 8 janelas seguidas acima da mediana (tendência de piora)" },
    lotsTitle: "Lotes no período",
    lotsSub: "Aceite pelo IC 95% da % de podres contra a especificação da linha (máx. {max}).",
    lotsEmpty: "Nenhum lote registrado no período.",
    lotCols: { lot: "Lote", n: "Frutas", rotten: "% podres (IC 95%)", poor: "% baixa qualidade", verdict: "Situação" },
    verdicts: { aprovado: "Aprovado", reprovado: "Reprovado", inconclusivo: "Inconclusivo", sem_dados: "Sem dados" },
    size: "Diâmetro mediano {m} mm (10% a 90%: {lo} a {hi} mm)",
    empty: "Sem frutas registradas neste período para esta câmera.",
    emptyDemo: "Para ver a linha com dados de demonstração: python manage.py seed_line_demo",
    demoBadge: "Dados sintéticos",
    fruitsAxis: "frutas",
    failed: "Não foi possível atualizar os dados da linha. Tentando de novo em 15 s.",
  },
  help: {
    open: "Abrir o guia do usuário",
    title: "Guia do usuário",
    close: "Fechar guia",
    lead: "Tudo o que você precisa para operar o FruitCam_ai. Atalho: a tecla ? abre este guia; Esc fecha.",
    contents: "Conteúdo",
    sections: [
      { id: "o-que-faz", title: "O que o sistema faz", body: ["Uma câmera fixa sobre a esteira filma as frutas que passam. Para cada fruta, o sistema mede o tamanho, sugere se é boa, de baixa qualidade ou podre e registra a hora, a linha e o lote.", "Com esses registros, a página Linha mostra quantas frutas passam por minuto, a proporção de cada classe com intervalo de confiança, alarmes quando a podridão sobe e o aceite de cada lote."] },
      { id: "linha", title: "Página Linha: o painel da esteira", body: ["Escolha a câmera, o período (30 min a 24 h) e a origem dos dados. “Câmeras reais” mostra só o que câmeras de verdade registraram; “Demonstração” mostra dados sintéticos, sempre com o selo de dados sintéticos.", "O quadro ao vivo se atualiza a cada segundo enquanto a câmera estiver ligada. Os números e gráficos se atualizam a cada 15 segundos."] },
      { id: "caixas", title: "Como ler o quadro da câmera", body: ["Caixa fina branca: fruta sendo seguida, ainda não contada. Caixa colorida: fruta já contada ao cruzar a linha tracejada.", "Verde = boa. Amarelo = baixa qualidade. Laranja = podre. Rosa = revisar (confiança baixa). O número ao lado é a confiança do modelo, não a garantia de acerto."] },
      { id: "indicadores", title: "Indicadores e IC 95%", body: ["Frutas por minuto conta só janelas completas. Cada porcentagem vem com o intervalo de confiança de 95% (Wilson): com poucas frutas, o intervalo é largo e o número ainda não é confiável.", "“Para revisão” são frutas que o sistema não quis decidir sozinho. Elas não entram nas porcentagens de classe até alguém conferir."] },
      { id: "carta", title: "Carta de controle e alarmes", body: ["Cada ponto é a % de podres de uma janela. A linha do meio é a mediana do período; a faixa é o limite p′ de Laney (3σ), que considera a variação normal entre janelas, além do acaso.", "Alarme “acima do limite”: a janela piorou além do esperado. Alarme “8 seguidas acima da mediana”: tendência de piora. Ao ver um alarme, confira o lote e o fornecedor daquele horário e a câmera (sujeira, luz)."] },
      { id: "lotes", title: "Lotes: aprovado, reprovado ou inconclusivo", body: ["Para cada lote, o sistema compara o IC 95% da % de podres com o máximo definido para a linha (em config/cameras.json).", "Aprovado: todo o intervalo está abaixo do máximo. Reprovado: todo o intervalo está acima. Inconclusivo: o intervalo cruza o máximo; precisa de mais frutas ou de inspeção manual."] },
      { id: "foto", title: "Inspeção por foto", body: ["Para conferir uma fruta fora da esteira: uma fruta por foto, fundo claro e liso, boa luz. O resultado mostra a probabilidade de cada classe.", "O aviso de revisão aparece quando o modelo não tem confiança suficiente para decidir. Com o modelo atual, ele aparece em todas as fotos: use as probabilidades como sugestão e confira a fruta."] },
      { id: "instalar", title: "Ligar uma câmera", body: ["1. Cadastre a câmera em config/cameras.json: nome, linha, endereço (rtsp://…, número da câmera USB ou arquivo de vídeo), px/mm, faixa da esteira na imagem e posição da linha de contagem.", "2. Inicie o leitor: python manage.py run_camera linha-1 (opcional: --lot L-0412). Ele grava um registro por fruta e o quadro mais recente.", "3. Calibre: meça um objeto de tamanho conhecido para acertar px/mm; ilumine de forma uniforme; use esteira de cor que contraste com as frutas."] },
      { id: "limites", title: "Limites atuais (leia antes de decidir)", body: ["O classificador atual é fraco: nas fotos de teste, a acurácia balanceada fica perto de 50% (o acaso seria 33%), e nenhum limiar de confiança chega a 95% de acerto. Por isso toda fruta classificada pelo modelo vai para conferência manual. Contagem, tamanho, carta de controle e aceite de lote não dependem disso.", "Os dados públicos de treino (Universidade Makerere) têm a numeração de classes trocada em 1.466 das 3.098 fotos; essas fotos foram excluídas. Um modelo anterior que parecia acertar 80,9% tinha aprendido esse erro.", "As fotos de treino são de cajus no pé, não de esteira. Antes de usar o sistema para rejeitar lotes, grave bandejas separadas à mão na sua esteira (comando record_tray) e treine de novo.", "“Baixa qualidade” no treino corresponde a frutos imaturos. Amassado, rachado e queimado não estão nos dados. Castanha e melão não têm fotos de treino. Frutas encostadas umas nas outras podem ser contadas como uma só."] },
    ],
  },
  credits: {
    title: "Créditos e licenças",
    lead: "Todas as mídias são hospedadas neste servidor. Cada foto de terceiros aparece aqui com autor, licença, fonte e as modificações feitas.",
    thirdParty: "Fotos de terceiros",
    firstParty: "Material próprio",
    author: "Autor",
    license: "Licença",
    source: "Fonte",
    date: "Data original",
    retrieved: "Obtida em",
    modifications: "Modificações",
    usedIn: "Onde aparece",
    files: "Arquivos",
    use: "Uso",
    dataTitle: "Dados de treino e avaliação do modelo",
    dataLead: "Conjuntos de imagens de terceiros usados para treinar ou avaliar o classificador, com autores e licenças. Só o primeiro entra no modelo; os outros servem para avaliação. Essas imagens não são exibidas no app.",
    authors: "Autores",
    datasetUse: {
      cashew_makerere: { use: "Treino, validação e teste do classificador de três classes.", modifications: "Recortes quadrados das caixas de frutas, com as classes do artigo agrupadas em boa, baixa qualidade e podre. Os 1.466 arquivos de rótulo cuja numeração de classes difere da do artigo foram excluídos." },
      potatoes: { use: "Somente avaliação: segmentação, receita de treino e sensibilidade ao fundo numa esteira industrial real (batatas). Não entra no modelo do app.", modifications: "Cópias rotacionadas, espelhadas e quase idênticas agrupadas; nova divisão sem repetição entre treino e teste; recortes redimensionados para 128 px." },
      lemons: { use: "Somente avaliação: sensibilidade ao fundo (bancada de laboratório, não esteira). Não entra no modelo do app.", modifications: "Rótulo por imagem a partir das regiões anotadas (o pior defeito decide); todas as fotos de um mesmo limão no mesmo conjunto; imagens redimensionadas para 128 px." },
      fruitnet: { use: "Baixado para avaliação futura (fotos de celular, não esteira). Não entra no modelo do app.", modifications: "Imagens “Mistas” excluídas; fotos quase idênticas agrupadas antes da divisão; imagens redimensionadas para 128 px." },
    },
  },
  fruits: { caju: "Caju", castanha: "Castanha", melao: "Melão" },
  deformities: { podre: "Podre", baixa_qualidade: "Baixa qualidade", queimada: "Queimada", quebrada: "Quebrada" },
  classes: { boa: "Boa", baixa_qualidade: "Baixa qualidade", podre: "Podre", revisar: "Revisar", nao_podre: "Não podre", indefinido: "Revisar" },
  seasons: { summer: "Verão", autumn: "Outono", winter: "Inverno", spring: "Primavera", rainy: "Chuvosa", dry: "Seca" },
  months: ["jan", "fev", "mar", "abr", "mai", "jun", "jul", "ago", "set", "out", "nov", "dez"],
  filters: {
    title: "Filtros",
    period: "Período",
    week: "Semana",
    month: "Mês",
    sector: "Setor",
    allSectors: "Todos os setores",
    start: "De",
    end: "Até",
    source: "Dados",
    real: "Reais",
    demo: "Demonstração",
    all: "Reais + demonstração",
    clear: "Limpar datas",
  },
  dashboard: {
    title: "Painel estatístico",
    subtitle: "Cada gráfico responde a uma pergunta; toque em “Como ler” para um tour rápido. Com poucos dados, trate os resultados como descritivos.",
    filterBar: "Período e setor",
    filterMore: "Intervalo de datas e origem dos dados",
    sections: {
      overview: { title: "Visão geral", lead: "Volume inspecionado, taxa de podres e comparação entre setores no período filtrado." },
      now: { title: "Qualidade agora", lead: "Qual defeito domina em cada semana e quais frutas chegam em maior quantidade." },
      trends: { title: "Tendências", lead: "Se boas e podres estão aumentando, lado a lado, e em que época do ano o crescimento se concentra." },
      distributions: { title: "Distribuições", lead: "Se a % de podres de cada setor segue uma curva normal, com o gráfico Q-Q ao lado." },
      forecast: { title: "Previsão", lead: "A % de podres esperada para o próximo período em cada setor, com o intervalo de previsão." },
    },
    loading: "Carregando gráfico…",
    noData: "Sem dados para os filtros escolhidos.",
    noRealData: "Ainda não há inspeções reais. Para a apresentação, escolha “Demonstração” em Dados.",
    fruitsUnit: "frutas",
    rottenUnit: "frutas podres",
    periodsUnit: "períodos",
  },
  badges: {
    n: "n = {n}",
    nPeriods: "n = {n} períodos",
    demo: "Dados de demonstração",
    small: "Amostra pequena",
    smallLatest: "A semana mais recente tem só {n} frutas podres.",
    smallTotal: "Só {n} frutas no período filtrado.",
    fewPeriods: "Só {n} períodos completos: variações podem ser ruído.",
    unreliable: "Não confiável",
    poorFit: "Ajuste ruim",
    partial: "Parciais fora",
    oneType: "1 tipo de defeito",
  },
  empty: {
    noDataTitle: "Sem dados",
    noDataDetail: "Nenhuma inspeção corresponde aos filtros escolhidos.",
    errorTitle: "Não foi possível carregar",
    insufficientTitle: "Dados insuficientes",
  },
  tour: {
    how: "Como ler",
    label: "Como ler este gráfico",
    step: "Passo {i} de {n}",
    prev: "Voltar",
    next: "Próximo",
    done: "Concluir",
    skip: "Pular",
  },
  cards: {
    deformity: {
      title: "Qual defeito domina cada semana?",
      subtitle: "Cor cheia = defeito dominante da semana; cada barra soma 100% das podres.",
      finding: "Na semana de {week}, {type} domina com {share} das frutas podres.",
      none: "Nenhuma fruta podre no período.",
      tie: "empate",
      oneTypeHint: "O modelo atual só distingue “podre”; outros tipos exigem retreinar o modelo.",
      steps: [
        "Cada cor é um tipo de defeito.",
        "Cada barra é uma semana; as cores somam 100% das frutas podres daquela semana.",
        "A cor cheia marca o defeito que dominou a semana; as apagadas são os demais.",
        "n = total de frutas podres por trás do gráfico.",
      ],
    },
    forecast: {
      title: "Algum setor vai mandar mais podres que boas?",
      subtitle: "Linha cheia = histórico; tracejado e leque = previsão com intervalo de 95%.",
      half: "50%",
      window: "últimos {n} períodos",
      predicted: "{arrow} {pred} previsto",
      chance: "chance de + podres: {p}",
      finding: "{sector}: previsão de {pred} de podres no próximo período; chance de mais podres que boas {p}.",
      findingEmpty: "{sector}: dados insuficientes para prever ({n} períodos).",
      emptyTitle: "Dados insuficientes",
      emptyDetail: "{n} de {min} períodos mínimos (com ≥ {fruits} frutas cada)",
      tipHistory: "{v} podres · n = {n} frutas",
      tipForecast: "Previsto {pred} (IC 95%: {lo} a {hi})",
      tipBacktest: "Teste retroativo: erro {mae} vs. {naive} da previsão ingênua",
      reasons: {
        insufficient_data: "dados insuficientes",
        few_periods: "menos de {min} períodos",
        no_backtest: "sem teste retroativo possível",
        not_better_than_naive: "não supera a previsão ingênua",
      },
      steps: [
        "A linha cheia mostra a % de podres do setor em cada período.",
        "Acima da linha de 50%, o setor manda mais podres que boas.",
        "O tracejado leva à previsão do próximo período.",
        "O leque é o intervalo de 95%: quanto mais largo, mais incerta a previsão.",
      ],
    },
    fruits: {
      title: "Qual fruta chega em maior quantidade?",
      subtitle: "Barra em destaque = fruta mais recebida no período filtrado.",
      winner: "mais recebida",
      tie: "empate",
      tip: "{n} frutas ({share})",
      finding: "{fruit} é a mais recebida: {n} frutas ({share}).",
      findingTie: "Empate entre as frutas mais recebidas.",
      steps: [
        "A barra destacada é a fruta que mais chegou.",
        "O comprimento da barra é o número de frutas.",
        "n = total de frutas no período filtrado.",
      ],
    },
    goodGrowth: { title: "As frutas boas estão aumentando?" },
    rottenGrowth: { title: "As frutas podres estão aumentando?" },
    growth: {
      subtitle: "Barra = variação da contagem vs. período anterior; tracejado = variação da proporção.",
      countLabel: "Variação da contagem",
      up: "Alta",
      down: "Queda",
      prop: "Variação da proporção",
      finding: "{kind}: {value} em {label} em relação ao período anterior.",
      findingNone: "Sem variação calculável no período.",
      insufficient: "É preciso pelo menos 2 períodos completos para calcular crescimento.",
      excludedTitle: "{n} frutas de períodos incompletos nas pontas ficaram fora do cálculo.",
      undefined: "indefinido",
      steps: [
        "A linha do zero significa “igual ao período anterior”.",
        "Barra azul para cima: cresceu em relação ao período anterior.",
        "Barra laranja para baixo: caiu.",
        "n/d: o período anterior era zero ou vazio; o crescimento é indefinido, não zero.",
      ],
    },
    recurring: {
      title: "Em que época do ano o crescimento se concentra?",
      subtitle: "Mediana do crescimento por semana do ano, mês ou estação; barra cheia = pico.",
      tabs: { week: "Semana do ano", month: "Mês", season: "Estação" },
      peak: "pico {kind}",
      finding: "Por {view}: pico das podres em {rot} ({rv}); das boas em {good} ({gv}).",
      smallTitle: "Cada barra vem de no máximo {n} período(s): ainda não é um padrão recorrente.",
      emptyDetail: "Não há períodos completos suficientes nesta escala.",
      steps: [
        "Troque a escala: semana do ano, mês ou estação.",
        "A barra cheia laranja é o pico de crescimento das podres.",
        "A barra cheia verde é o pico de crescimento das boas.",
        "n = frutas usadas; o selo “Amostra pequena” avisa quando cada barra vem de poucos períodos.",
      ],
    },
    gaussian: {
      title: "A % de podres de cada setor segue uma curva normal?",
      subtitle: "Barras = períodos reais; curva = normal ajustada; faixas = ±1σ e ±2σ.",
      hist: "Períodos observados",
      pdf: "Curva normal ajustada",
      qq: "Gráfico Q-Q",
      qqLine: "reta = normal perfeita",
      mean: "média {v}",
      s1: "±1σ",
      s2: "±2σ",
      impossible: "impossível",
      poor: "Ajuste ruim",
      poorSub: "Shapiro p = {p}",
      tipBin: "{from} a {to}: {n} períodos",
      finding: "{sector}: média de {mean} de podres, desvio {std}, {n} períodos.",
      findingPoor: "Ajuste ruim: não trate como curva normal.",
      qqFinding: "{sector}, gráfico Q-Q: Shapiro-Wilk W = {w}, p = {p}.",
      emptyTitle: "Poucos períodos",
      emptyDetail: "{n} períodos; o histograma precisa de pelo menos 3 com variação.",
      reasons: {
        small_n: "menos de {min} períodos",
        no_variance: "sem variação",
        not_normal: "teste rejeita normalidade (p < {alpha})",
        outside_01: "curva prevê proporções fora de 0–100%",
      },
      steps: [
        "Cada barra conta quantos períodos tiveram aquela % de podres.",
        "A linha escura marca a média.",
        "Faixa escura = ±1σ e clara = ±2σ: numa curva normal, ~68% e ~95% dos períodos caem nelas.",
        "No Q-Q, pontos sobre a reta indicam forma normal; curvas nas pontas indicam desvio.",
      ],
    },
    overview: {
      title: "Como está a inspeção no geral?",
      subtitle: "Volume, taxa de podres e comparação entre setores no período filtrado.",
      volume: "Volume por período",
      rate: "Taxa de podres",
      sectors: "Taxa de podres por setor",
      total: "frutas",
      rateCounter: "podres",
      sectorsCounter: "setores",
      avg: "média",
      findingVolume: "{n} frutas inspecionadas no período filtrado.",
      findingRate: "Taxa de podres no período: {v}.",
      findingSectors: "Maior taxa de podres: {sector}, com {v}.",
      steps: [
        "Volume por período: verde = boas, laranja = podres.",
        "A linha mostra a % de podres em cada período; o tracejado é a média.",
        "O setor com a maior taxa de podres fica em destaque.",
        "n = total de frutas consideradas.",
      ],
    },
  },
  charts: {
    good: "Boas",
    rotten: "Podres",
    count: "Frutas",
    na: "n/d",
    history: "Histórico",
    forecast: "Previsão",
    bandHigh: "Limite superior (95%)",
    bandLow: "Limite inferior (95%)",
    frequency: "Frequência",
    theoretical: "Quantil teórico",
    observed: "Quantil observado",
    weekOf: "Semana de {week}",
    nRotten: "n = {n} podres",
    nFruits: "n = {n} frutas",
    nPeriods: "n = {n} períodos",
  },
  errors: {
    invalid_credentials: "Usuário ou senha incorretos.",
    throttled: "Muitas tentativas. Tente de novo em {s} segundos.",
    not_authenticated: "Sua sessão expirou. Entre novamente.",
    csrf_failed: "Sessão de segurança expirada. Recarregue a página e tente de novo.",
    image_required: "Escolha uma foto.",
    invalid_sector: "Informe o setor (até 50 caracteres).",
    invalid_fruit_type: "Escolha caju, castanha ou melão.",
    unsupported_type: "Formato não aceito. Use JPEG, PNG ou WebP.",
    invalid_image: "O arquivo não é uma imagem válida ou está corrompido.",
    file_too_large: "Arquivo maior que {mb} MB.",
    image_too_large: "Imagem com resolução grande demais.",
    invalid_filter: "Filtro inválido.",
    not_found: "Recurso não encontrado.",
    method_not_allowed: "Operação não permitida.",
    network_error: "Sem conexão com o servidor.",
    server_error: "Erro interno do servidor. Tente de novo.",
    unknown: "Algo deu errado.",
  },
};

export function fill(text, vars = {}) {
  return text.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? vars[k] : `{${k}}`));
}

export function errorText(err) {
  const code = err?.code || "unknown";
  return fill(t.errors[code] || t.errors.unknown, { s: err?.info?.wait_seconds ?? "", mb: err?.info?.max_mb ?? "" });
}
